### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by gewaechshaus** [encomage/module-guestbook#2]
Hey @VadimSapa @andrey-bondarenko ,

the pager doesn't work in our case, it always returns the same collection... Can you verify that?

Greetings
Jan

**Comment by gewaechshaus** [comment]
Returns bool false:

https://github.com/encomage/module-guestbook/blob/df775f8454f95b8b4f9021f69798fbceed47afad/Block/Comments.php#L217

**Comment by andrey-bondarenko** [comment]
@gewaechshaus 

It will be fixed today or tomorrow

**Comment by gewaechshaus** [comment]
@andrey-bondarenko  - thanks! I think the p param is never use to setCurPage and there are some other issues related to the collection object as well.

**Comment by andrey-bondarenko** [comment]
@gewaechshaus It was a mistake. This functionality hasn't implemented yet. We will implement it for the next week.

**Comment by gewaechshaus** [comment]
OK

**Comment by gewaechshaus** [comment]
Hey @andrey-bondarenko - are there any news related to the pagination?

Greetings
Jan

**Comment by andrey-bondarenko** [comment]
@gewaechshaus Hi sorry about that. We have a very high loading now. We will do it ASAP.

Thanks!

**Comment by gewaechshaus** [comment]
@andrey-bondarenko - may I ask you again about the state of the pagination?

Many thanks, Cheers, Jan

**Comment by andrey-bondarenko** [comment]
@gewaechshaus 
Hi, we're going to fix it the next week.

Thanks

**Comment by gewaechshaus** [comment]
@andrey-bondarenko - sorry for asking again - any news about the state of the pagination?

Cheers
Jan

**Comment by andrey-bondarenko** [comment]
@gewaechshaus Hi, sorry for delay and thanks for waiting. It will be released tomorrow.

**Comment by andrey-bondarenko** [comment]
@gewaechshaus done. please update module.

**Comment by gewaechshaus** [comment]
@andrey-bondarenko - many many thanks! We found 2 issues, I will create a PR...

Cheers
Jan

**Comment by andrey-bondarenko** [comment]
@gewaechshaus Great! Thanks!

**Comment by gewaechshaus** [comment]
https://github.com/encomage/module-guestbook/pull/5

**Comment by gewaechshaus** [comment]
There's a small issue with the loader, I have to look at it later
`Expected to start loader but did not find one in the dom`
